version: '3'

networks:
  default:
    name: nginx-services

services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    ports:
      - 51820:51820/udp
    environment:
      - WG_HOST=${NGINX_HOST}
      - PASSWORD=${WG_PASS}
    volumes:
      -  ${CONFIG_DIR}/wg-easy:/etc/wireguard
    cap_add:
        - NET_ADMIN
        - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
