version: '3'

networks:
  default:
    name: nginx-services

services:
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ${CONFIG_DIR}/certbot/www/:/var/www/certbot/:rw
      - ${CONFIG_DIR}/certbot/conf/:/etc/letsencrypt/:rw
