apiVersion: v1
kind: PersistentVolume
metadata:
  name: documents-pv
  labels:
    app: documents-pv-selector
spec:
  capacity:
    storage: 100Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/ext-storage/documents"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: documents-pvc
  namespace: default
spec:
  selector: 
    matchLabels:
      app: documents-pv-selector
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Gi
