apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-db-pv
  labels:
    app: filebrowser-pv-selector
spec:
  capacity:
    storage: 1Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/storage/config/filebrowser/database.db"
    type: File
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-db-pvc
  namespace: default
spec:
  selector: 
    matchLabels:
      app: filebrowser-pv-selector
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
