apiVersion: v1                      
kind: PersistentVolume              
metadata:                           
  name: freshrss-config-pv          
spec:                               
  capacity:                         
    storage: 1Gi                    
  storageClassName: local-storage   
  accessModes:                      
    - ReadWriteOnce                 
  hostPath:                         
    path: "/storage/config/freshrss"
---                                 
apiVersion: v1                      
kind: PersistentVolumeClaim         
metadata:                           
  name: freshrss-config-pvc         
spec:                               
  accessModes:                      
    - ReadWriteOnce                 
  storageClassName: local-storage   
  resources:                        
    requests:                       
      storage: 1Gi                  
