apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-db-pv
spec:
  capacity:
    storage: 3Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/config/freshrss-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 3Gi
