apiVersion: v1                      
kind: PersistentVolume              
metadata:                           
  name: immich-db-pv          
  namespace: immich
spec:                               
  capacity:                         
    storage: 5Gi                    
  storageClassName: local-storage   
  accessModes:                      
    - ReadWriteOnce                 
  hostPath:                         
    path: "/storage/config/immich-db"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - dietpi
---                                 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-db-pvc         
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage   
  resources:
    requests:
      storage: 5Gi
