apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-db-pv
  labels:
    app: immich-db-pv-selector
spec:
  capacity:
    storage: 5Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/storage/config/immich-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-db-pvc
  namespace: default
spec:
  selector: 
    matchLabels:
      app: immich-db-pv-selector
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
