apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-config-pv
  labels:
    app: nginx-pv-selector
spec:
  capacity:
    storage: 1Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/storage/config/nginx"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-config-pvc
  namespace: default
spec:
  selector: 
    matchLabels:
      app: nginx-pv-selector
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
