apiVersion: v1                      
kind: PersistentVolume              
metadata:                           
  name: organizr-config-pv          
  namespace: default
spec:                               
  capacity:                         
    storage: 1Gi                    
  storageClassName: local-storage   
  accessModes:                      
    - ReadWriteOnce                 
  hostPath:                         
    path: "/storage/config/organizr"
---                                 
apiVersion: v1                      
kind: PersistentVolumeClaim         
metadata:                           
  name: organizr-config-pvc         
  namespace: default
spec:                               
  accessModes:                      
    - ReadWriteOnce                 
  storageClassName: local-storage   
  resources:                        
    requests:                       
      storage: 1Gi
