apiVersion: v1
kind: PersistentVolume
metadata:
  name: photos-pv
spec:
  capacity:
    storage: 300Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/ext-storage/photos"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 300Gi
