apiVersion: v1
kind: PersistentVolume
metadata:
  name: rss-pv
  labels:
    app: rss-selector
spec:
  capacity:
    storage: 1Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/storage/rss"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rss-pvc
  namespace: default
spec:
  selector: 
    matchLabels:
      app: rss-selector
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
