apiVersion: v1                      
kind: PersistentVolume              
metadata:                           
  name: wireguard-config-pv          
  namespace: default
spec:                               
  capacity:                         
    storage: 1Gi                    
  storageClassName: local-storage   
  accessModes:                      
    - ReadWriteOnce                 
  hostPath:                         
    path: "/storage/config/wireguard"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - dietpi
---                                 
apiVersion: v1                      
kind: PersistentVolumeClaim         
metadata:                           
  name: wireguard-config-pvc         
  namespace: default
spec:                               
  accessModes:                      
    - ReadWriteOnce                 
  storageClassName: local-storage   
  resources:                        
    requests:                       
      storage: 1Gi
