replicas: 1
namespace: default
appName: example

image:
  repository: example/example
  tag: latest

ports:
  containerPort: 9999
  servicePort: 9999

ingress:
  host: host.com
  hostPrefix: example
  sslSecretName: ssl-certificate

env:
  example:
    name: example
    value: example

volumes:
  config:
    name: example-config
    pvc:
      mount: /config
      claimName: example-config-pvc
