version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - ${CONFIG_DIR}/filebrowser/data:/srv
      - ${CONFIG_DIR}/filebrowser/filebrowser.db:/database.db

