version: '3'

networks:
  default:
    name: nginx-services

services:
  flood:
    image: jesec/flood
    environment:
      HOME: /config
    container_name: flood
    volumes:
      - ${CONFIG_DIR}/flood/:/config
    ports:
      - "3000:3000"
    restart: unless-stopped
