version: '3'

networks:
  default:
    name: nginx-services

services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_DIR}/freshrss:/config
    restart: unless-stopped

  freshrss-db:
    image: postgres:16.1-alpine
    container_name: freshrss-db
    environment:
      - POSTGRES_USER=freshrss
      - POSTGRES_PASSWORD=freshrss
      - POSTGRES_DB=freshrss
    restart: unless-stopped
