version: '3'

networks:
  default:
    name: nginx-services

services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ${CONFIG_DIR}/homer/:/www/assets
    ports:
      - "8080:8080"
    restart: unless-stopped
