version: '3'

networks:
  default:
    name: nginx-services

volumes:
  nextcloud:
  nextcloud_db:

services:
  nextcloud_db:
    image: postgres:14
    container_name: nextcloud_db
    restart: unless-stopped
    volumes:
      - nextcloud_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${NEXTCLOUD_DB_NAME}
      - POSTGRES_USER=${NEXTCLOUD_DB_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASS}
  
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    links:
      - nextcloud_db
    volumes:
      - nextcloud:/var/www/html
      - ${NEXTCLOUD_EXT_STORAGE}:/external
    environment:
      - POSTGRES_DB=${NEXTCLOUD_DB_NAME}
      - POSTGRES_USER=${NEXTCLOUD_DB_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASS}
      - POSTGRES_HOST=nextcloud_db
      - REDIS_HOST=redis
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=8192M
      - NEXTCLOUD_TRUSTED_DOMAINS=${NGINX_HOST}
