version: '3'

networks:
  default:
    name: nginx-services

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
    - ${NGINX_CONFIG_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro
    - ${NGINX_CONFIG_DIR}/proxy_params:/etc/nginx/proxy_params
    - ${NGINX_CONFIG_DIR}/sites-enabled/:/etc/nginx/sites-enabled
    - ${NGINX_CONFIG_DIR}/ssl_common/:/etc/nginx/ssl_common
    - ${CONFIG_DIR}/nginx/:/usr/share/nginx
    - ${CONFIG_DIR}/certbot/www:/var/www/certbot/:ro
    - ${CONFIG_DIR}/certbot/conf/:/etc/nginx/ssl/:ro
    ports:
    - "80:80"
    - "443:443"
    environment:
    - NGINX_HOST=${NGINX_HOST}
    - NGINX_PORT=80
    # links:
    #   - php-fpm
    restart: unless-stopped
