version: '3'

networks:
  default:
    name: nginx-services

services:
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: always
    ports:
      - 8182:80
    environment:
      - ${CONFIG_DIR}/onlyoffice/logs:/var/log/onlyoffice
      - ${CONFIG_DIR}/onlyoffice/data:/var/www/onlyoffice/Data
      - JWT_SECRET=${ONLYOFFICE_JWT}
