version: '3'

networks:
  default:
    name: nginx-services

services:
  php-fpm:
    build: 
      context: ./dockerfile/
      dockerfile: php-fpm
    container_name: php-fpm
    volumes:
      - ${CONFIG_DIR}/nginx/:/usr/share/nginx

