version: '3'

networks:
  default:
    name: nginx-services

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${RADARR_MOVIES_DIR}:/movies #optional
      - ${RADARR_DOWNLOAD_DIR}:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
