version: '3'

networks:
  default:
    name: nginx-services

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${SYNCTHING_DATA_DIR}:/data
      - ${CONFIG_DIR}/syncthing:/config
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
