version: '3'

networks:
  default:
    name: nginx-services

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
      # - TRANSMISSION_WEB_HOME= #optional
      # - WHITELIST= #optional
      # - PEERPORT= #optional
      # - HOST_WHITELIST= #optional
    volumes:
      - ${TRANSMISSION_DOWNLOAD_DIR}:/downloads
      - ${CONFIG_DIR}/transmission:/config
      # - /path/to/watch/folder:/watch
    restart: unless-stopped
