#!/bin/bash

yml_directory="/home/binh/self-hosted/services"
project_directory="/home/binh/self-hosted/"

yml_files=()
enabled_services=(
  "gitea.yml"
  "immich.yml"
  "nginx.yml"
)
disabled_services=(
  "aria.yml"
  "bazarr.yml"
  "dozzle.yml"
  "flaresolverr.yml"
  "flood.yml"
  "hedgedoc.yml"
  "jellyfin.yml"
  "jellyseerr.yml"
  "libreddit.yml"
  "organizr.yml"
  "prowlarr.yml"
  "radarr.yml"
  "sonarr.yml"
  "vikunja.yml"
  "transmission.yml"
  "calorie-tracker.yml"
  "mirekng.yml"
  "nexus.yml"
  "symfony-api.yml"
  "event-manager.yml"
  "nextcloud.yml"
  "freshrss.yml"
  "homer.yml"
  "pihole.yml"
  "home-assistant.yml"
  "filebrowser.yml"
  "php-fpm.yml"
  "calorie-tracker.yml"
  "mailer.yml"
  "uptime-kuma.yml"
  "ntfy.yml"
  "syncthing.yml"
  "wireguard.yml"
  "monica.yml"
  "memos.yml"
  "grafana.yml"
);

for service in "${enabled_services[@]}"; do
    file="$yml_directory/$service"
    if [ -f "$file" ]; then
        yml_files+=("-f $file")
    fi
done
compose="sudo docker-compose --project-directory="$project_directory" "${yml_files[@]}" $@"
eval "$compose"
