#!/bin/bash

yml_directory="/home/binh/self-hosted/docker-services"
project_directory="/home/binh/self-hosted/"

yml_files=()

for file in "$yml_directory"/*.yml; do
    if [ -f "$file" ]; then
        yml_files+=("-f $file")
    fi
done
compose="sudo docker-compose --project-directory="$project_directory" "${yml_files[@]}" down"
eval "$compose"
