version: '3'

networks:
  default:
    name: nginx-services

volumes:
  nextcloud:
  nextcloud_db:
  gitea_db:
  moodledb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
  #  tube_cache:
  #  tube_redis:
  #  tube_es:



services:
# Nginx ----------------------------------------------------------------------------------
  nginx:
    image: nginx
    container_name: nginx
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/proxy_params:/etc/nginx/proxy_params
    - ./config/nginx/src/:/usr/share/nginx/html
    - ./config/certbot/www:/var/www/certbot/:ro
    - ./config/certbot/conf/:/etc/nginx/ssl/:ro
    ports:
    - "80:80"
    - "443:443"
    environment:
    - NGINX_HOST=${NGINX_HOST}
    - NGINX_PORT=80
    links:
      - php-fpm
# php-fpm ----------------------------------------------------------------------------------
  php-fpm:
    image: php:8-fpm
    container_name: php-fpm
    volumes:
      - ./config/nginx/src:/usr/share/nginx/html
# certbot ----------------------------------------------------------------------------------
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./config/certbot/www/:/var/www/certbot/:rw
      - ./config/certbot/conf/:/etc/letsencrypt/:rw
# Transmission ----------------------------------------------------------------------------------
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
      # - TRANSMISSION_WEB_HOME= #optional
      # - WHITELIST= #optional
      # - PEERPORT= #optional
      # - HOST_WHITELIST= #optional
    volumes:
      - ${TRANSMISSION_DOWNLOAD_DIR}:/downloads
      - ./config/transmission:/config
      # - /path/to/watch/folder:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
# Gitea ----------------------------------------------------------------------------------
  #  gitea:
  #    image: gitea/gitea
  #    container_name: gitea
  #    environment:
  #      - USER_UID=1000
  #      - USER_GID=1000
  #      - GITEA__database__DB_TYPE=postgres
  #      - GITEA__database__HOST=gitea_db:5432
  #      - GITEA__database__NAME=${GITEA_DB_NAME}
  #      - GITEA__database__USER=${GITEA_DB_USER}
  #      - GITEA__database__PASSWD=${GITEA_DB_PASS}
  #    restart: always
  #    volumes:
  #      - ./config/gitea:/data
  #      - /etc/timezone:/etc/timezone:ro
  #      - /etc/localtime:/etc/localtime:ro
  #    ports:
  #      - "3000:3000"
  #      - "222:22"
  #    depends_on:
  #      - gitea_db
  #  gitea_db:
  #    image: postgres:14
  #    container_name: gitea_db
  #    restart: always
  #    volumes:
  #      - gitea_db:/var/lib/postgresql/data
  #    environment:
  #      - POSTGRES_DB=gitea
  #      - POSTGRES_USER=gitea
  #      - POSTGRES_PASSWORD=gitea
# Moodle ----------------------------------------------------------------------------------
  #  moodle:
  #    image: docker.io/bitnami/moodle:4.2
  #    container_name: moodle
  #    ports:
  #      - '8080:8080'
  #    environment:
  #      - MOODLE_DATABASE_TYPE=pgsql
  #      - MOODLE_DATABASE_HOST=moodle_db
  #      - MOODLE_DATABASE_PORT_NUMBER=5432
  #      - MOODLE_DATABASE_NAME=${MOODLE_DB_NAME}
  #      - MOODLE_DATABASE_USER=${MOODLE_DB_USER}
  #      - MOODLE_DATABASE_PASSWORD=${MOODLE_DB_PASS}
  #      - MOODLE_USERNAME=${MOODLE_USER}
  #      - MOODLE_PASSWORD=${MOODLE_PASS}
  #      - PHP_UPLOAD_MAX_FILESIZE=8192M
  #      - PHP_POST_MAX_SIZE=8192M
  #      - PHP_ENABLE_OPCACHE=yes
  #    volumes:
  #      - 'moodle_data:/bitnami/moodle'
  #      - 'moodledata_data:/bitnami/moodledata'
  #    depends_on:
  #      - moodle_db
  #  moodle_db:
  #    image: postgres:14
  #    container_name: moodle_db
  #    restart: always
  #    volumes:
  #      - moodledb_data:/var/lib/postgresql/data
  #    environment:
  #      - POSTGRES_DB=${MOODLE_DB_NAME}
  #      - POSTGRES_USER=${MOODLE_DB_USER}
  #      - POSTGRES_PASSWORD=${MOODLE_DB_PASS}
# Nextcloud ----------------------------------------------------------------------------------
  nextcloud_db:
    image: postgres:14
    container_name: nextcloud_db
    restart: always
    volumes:
      - nextcloud_db:/var/lib/postgresql/data
      # - /home/binh/volumes/self-hosted_nextcloud_db/_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${NEXTCLOUD_DB_NAME}
      - POSTGRES_USER=${NEXTCLOUD_DB_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASS}
  
  redis:
    image: redis
    container_name: redis
    restart: always

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 8181:80
    links:
      - nextcloud_db
    volumes:
      - nextcloud:/var/www/html
      # - /home/binh/volumes/self-hosted_nextcloud/_data:/var/www/html
      - ${NEXTCLOUD_EXT_STORAGE}:/external
    environment:
      - POSTGRES_DB=${NEXTCLOUD_DB_NAME}
      - POSTGRES_USER=${NEXTCLOUD_DB_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASS}
      - POSTGRES_HOST=nextcloud_db
      - REDIS_HOST=redis
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=8192M
      - NEXTCLOUD_TRUSTED_DOMAINS=${NGINX_HOST}
# Aria2 Web UI -------------------------------------------------------------------------------
  Aria2-Pro:
    image: p3terx/aria2-pro
    container_name: aria2-pro
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=${ARIA2_RPC_SECRET}
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=${TIMEZONE}
    volumes:
      - ./config/aria2:/config
      - ${ARIA2_DOWNLOAD_DIR}:/downloads
# If you use host network mode, then no port mapping is required.
# This is the easiest way to use IPv6 networks.
    # network_mode: host
#    network_mode: bridge
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    restart: unless-stopped
# Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m

# AriaNg is just a static web page, usually you only need to deploy on a single host.
  AriaNg:
    image: p3terx/ariang
    container_name: ariang
    command: --port 6880 --ipv6
#    network_mode: host
#    network_mode: bridge
    ports:
      - 6880:6880
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
# Jellyfin -------------------------------------------------------------------------------
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ./config/jellyfin:/config
      - ${JELLYFIN_ANIME_DIR}:/data/anime
      - ${JELLYFIN_TV_SHOWS_DIR}:/data/tv-shows
      - ${JELLYFIN_MOVIES_DIR}:/data/movies
      - ${JELLYFIN_OTHER_MEDIA_DIR}:/data/other-media
    ports:
      - 8096:8096
    restart: unless-stopped
# Sonarr -------------------------------------------------------------------------------
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ./config/sonarr:/config
      - ${SONARR_ANIME_DIR}:/anime #optional
      - ${SONARR_TV_SHOWS_DIR}:/tv-shows #optional
      - ${SONARR_DOWNLOAD_DIR}:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
# Radarr -------------------------------------------------------------------------------
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ./config/radarr:/config
      - ${RADARR_MOVIES_DIR}:/movies #optional
      - ${RADARR_DOWNLOAD_DIR}:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
# Bazarr -------------------------------------------------------------------------------
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ./config/bazarr:/config
      - ${BAZARR_MOVIES_DIR}:/downloads/movies #optional
      - ${BAZARR_TV_DIR}:/downloads/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
# Prowlarr -------------------------------------------------------------------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ./config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

# Jellyseerr -------------------------------------------------------------------------------
  jellyseerr:
      image: fallenbagel/jellyseerr:latest
      container_name: jellyseerr
      environment:
        - LOG_LEVEL=debug
        - TZ=${TIMEZONE}
      ports:
        - 5055:5055
      volumes:
        - ./config/jellyseerr:/app/config
      restart: unless-stopped

# Tube archivist -------------------------------------------------------------------------------
  #  tubearchivist:
  #    container_name: tubearchivist
  #    restart: unless-stopped
  #    image: bbilly1/tubearchivist
  #    ports:
  #      - 8000:8000
  #    volumes:
  #      - ${TUBE_MEDIA_DIR}:/youtube
  #      - tube_cache:/cache
  #    environment:
  #      - ES_URL=http://archivist-es:9200
  #      - REDIS_HOST=archivist-redis
  #      - HOST_UID=1000
  #      - HOST_GID=1000
  #      - TA_HOST=${TUBE_HOST}
  #      - TA_USERNAME=${TUBE_USER}
  #      - TA_PASSWORD=${TUBE_PASS}
  #      - ELASTIC_PASSWORD=${TUBE_ES_PASS}
  #      - TZ=${TIMEZONE}
  #    depends_on:
  #      - archivist-es
  #      - archivist-redis
  #  archivist-redis:
  #    image: redis/redis-stack-server
  #    container_name: archivist-redis
  #    restart: unless-stopped
  #    expose:
  #      - "6379"
  #    volumes:
  #      - tube_redis:/data
  #    depends_on:
  #      - archivist-es
  #  archivist-es:
  #    image: elasticsearch:8.7.0
  #    container_name: archivist-es
  #    restart: unless-stopped
  #    environment:
  #      - ELASTIC_PASSWORD=${TUBE_ES_PASS}
  #      - "ES_JAVA_OPTS=-Xms128m -Xmx512m"
  #      - "xpack.security.enabled=true"
  #      - "discovery.type=single-node"
  #      - "path.repo=/usr/share/elasticsearch/data/snapshot"
  #    ulimits:
  #      memlock:
  #        soft: -1
  #        hard: -1
  #    volumes:
  #      - tube_es:/usr/share/elasticsearch/data
  #    expose:
  #      - "9200"
