version: '3'

networks:
  default:
    name: nginx-services

services:
# Nginx ----------------------------------------------------------------------------------
# Nextcloud ----------------------------------------------------------------------------------
