apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-deployment"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ .Values.appName }}-deployment"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.appName }}-selector"
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: "{{ .Values.appName }}-selector"
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
            - containerPort: 6881
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Etc/UTC
            - name: WEBUI_PORT
              value: "8080"
            - name: TORRENTING_PORT
              value: "6881"
          volumeMounts:
            - mountPath: {{ .Values.volumes.media.pvc.mount }}
              name: {{ .Values.volumes.media.name }}
            - mountPath: {{ .Values.volumes.config.pvc.mount }}
              name: {{ .Values.volumes.config.name }}
      volumes:
        - name: {{ .Values.volumes.media.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.media.pvc.claimName }}
        - name: {{ .Values.volumes.config.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.config.pvc.claimName }}
