apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-load-balancer"
spec:
  type: LoadBalancer
  selector:
    app: "{{ .Values.appName }}-selector"
  ports:
    - port: 6881
      targetPort: 6881
