apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-service"
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: "{{ .Values.appName }}-selector"
  ports:
    - protocol: TCP
      targetPort: {{ .Values.ports.containerPort }}
      port: {{ .Values.ports.servicePort }}
