apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-certificate
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.ingress.sslSecretName }}
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "{{ .Values.ingress.host }}"
    - "*.{{ .Values.ingress.host }}"
