apiVersion: batch/v1
kind: Job
metadata:
  name: immich-db-init
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-extensions
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          command:
            - /bin/sh
            - -c
            - |
              until pg_isready -h immich-postgres-service -U {{ .Values.db.user }}; do
                echo "Waiting for postgres..."
                sleep 2
              done
              PGPASSWORD={{ .Values.db.password }} psql -h immich-postgres-service -U {{ .Values.db.user }} -d {{ .Values.db.name }} -c "CREATE EXTENSION IF NOT EXISTS vchord CASCADE;"
              PGPASSWORD={{ .Values.db.password }} psql -h immich-postgres-service -U {{ .Values.db.user }} -d {{ .Values.db.name }} -c "CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;"
              echo "Extensions created successfully"
