apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-ml
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-ml
  template:
    metadata:
      labels:
        app: immich-ml
    spec:
      containers:
        - name: machine-learning
          image: "{{ .Values.machineLearning.image.repository }}:{{ .Values.machineLearning.image.tag }}"
          ports:
            - containerPort: 3003
          env:
            - name: TRANSFORMERS_CACHE
              value: /cache
            - name: HF_XET_CACHE
              value: /cache/huggingface-xet
            - name: MPLCONFIGDIR
              value: /cache/matplotlib-config
          volumeMounts:
            - name: cache
              mountPath: /cache
      volumes:
        - name: cache
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: immich-ml-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: immich-ml
  ports:
    - port: 3003
      targetPort: 3003
