apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{ .Values.appName }}-secret-external"
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: "{{ .Values.appName }}-secret"
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: "PAPERCLIP_DATABASE_URL"
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: "PAPERCLIP_DATABASE_PASSWORD"
    - secretKey: BETTER_AUTH_SECRET
      remoteRef:
        key: "PAPERCLIP_BETTER_AUTH_SECRET"
    - secretKey: DEEPSEEK_API_KEY
      remoteRef:
        key: "PAPERCLIP_DEEPSEEK_API_KEY"
    - secretKey: PUBLIC_URL
      remoteRef:
        key: "PAPERCLIP_PUBLIC_URL"
