version: '3'

networks:
  default:
    name: nginx-services

services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TIMEZONE}
    ports:
      - 5055:5055
    volumes:
      - ${CONFIG_DIR}/jellyseerr:/app/config
    restart: unless-stopped
