apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-db-service"
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: "{{ .Values.appName }}-db"
  ports:
    - protocol: TCP
      targetPort: 5432
      port: 5432
