apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-service"
spec:
  selector:
    app: "{{ .Values.appName }}-selector"
  ports:
    - protocol: TCP
      targetPort: {{ .Values.ports.containerPort }}
      port: {{ .Values.ports.servicePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: freshrss-db
spec:
  selector:
    app: freshrss-postgres-selector
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
