apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: freshrss-postgres-statefulset
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: freshrss-postgres-selector
  template:
    metadata:
      labels:
        app: freshrss-postgres-selector
    spec:
      containers:
        - name: freshrss-db
          image: postgres:latest
          command: ["sh", "-c", "chown 1000:1000 /var/lib/postgresql"]
          ports:
            - containerPort: 5432
              name: freshrss-db
          env:
            - name: "POSTGRES_USER"
              value: "freshrss"
            - name: "POSTGRES_PASSWORD"
              value: "freshrss"
            - name: "POSTGRES_DB"
              value: "freshrss"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: freshrss-db-pvc
