apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-load-balancer"
spec:
  type: LoadBalancer
  selector:
    app: "{{ .Values.appName }}-selector"
  ports:
    - protocol: TCP
      name: vpn-tcp
      targetPort: 51820
      port: 51820
    - protocol: UDP
      name: vpn-udp
      targetPort: 51820
      port: 51820
