version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - ${CONFIG_DIR}/filebrowser/data:/srv/data
      - ${NEXTCLOUD_EXT_STORAGE}:/srv/downloads
      - ${UPLOAD_LOCATION}/library:/srv/photos
      - ${CONFIG_DIR}/filebrowser/filebrowser.db:/database.db
    healthcheck: 
      disable: true
    ports:
      - 3003:80
    restart: unless-stopped
