apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss-deployment
  labels:
    app: freshrss-deployment
spec:
  selector:
    matchLabels:
      app: freshrss-selector
  replicas: 1
  template:
    metadata:
      labels:
        app: freshrss-selector
    spec:
      containers:
        - name: freshrss
          image: lscr.io/linuxserver/freshrss:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /config
              name: freshrss-config
      volumes:
        - name: freshrss-config
          persistentVolumeClaim:
            claimName: freshrss-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: freshrss-service
spec:
  selector:
    app: freshrss-selector
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: freshrss-postgres-statefulset
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: freshrss-postgres-selector
  template:
    metadata:
      labels:
        app: freshrss-postgres-selector
    spec:
      containers:
        - name: freshrss-db
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: freshrss-db
          env:
            - name: "POSTGRES_USER"
              value: "freshrss"
            - name: "POSTGRES_PASSWORD"
              value: "freshrss"
            - name: "POSTGRES_DB"
              value: "freshrss"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: freshrss-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: freshrss-db
spec:
  selector:
    app: freshrss-postgres-statefulset
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-db-pv
spec:
  capacity:
    storage: 1Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/freshrss/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-config-pv
spec:
  capacity:
    storage: 1Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/freshrss/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
