version: '3'

networks:
  default:
    name: nginx-services

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/jellyfin:/config
      - ${JELLYFIN_ANIME_DIR}:/data/anime
      - ${JELLYFIN_TV_SHOWS_DIR}:/data/tv-shows
      - ${JELLYFIN_MOVIES_DIR}:/data/movies
      - ${JELLYFIN_OTHER_MEDIA_DIR}:/data/other-media
    devices:
      - /dev/dri/:/dev/dri/
    security_opt:
      - label=disable
    restart: unless-stopped
