version: '3'

networks:
  default:
    name: nginx-services

services:
  mailer:
    image: mireknguyen/mailer
    container_name: mirekng-mailer
    environment:
      - MAILER_HOST=${MAILER_HOST}
      - MAILER_USER=${MAILER_USER}
      - MAILER_PASS=${MAILER_PASS}
      - MAILER_EMAIL_TO=${MAILER_EMAIL_TO}
      - MAILER_PORT=${MAILER_PORT:-25}
    restart: unless-stopped

