apiVersion: apps/v1
kind: Deployment
metadata:
  name: organizr-deployment
  labels:
    app: organizr-deployment
spec:
  selector:
    matchLabels:
      app: organizr-selector
  replicas: 1
  template:
    metadata:
      labels:
        app: organizr-selector
    spec:
      containers:
        - name: organizr
          image: organizr/organizr:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /config
              name: organizr-config
      volumes:
        - name: organizr-config
          persistentVolumeClaim:
            claimName: organizr-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: organizr-service
spec:
  selector:
    app: organizr-selector
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: organizr-config-pv
spec:
  capacity:
    storage: 1Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/organizr/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: organizr-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
