apiVersion: v1                      
kind: PersistentVolumeClaim         
metadata:                           
  name: {{ .Values.appName }}-config-pvc         
spec:                               
  storageClassName: {{ .Values.volumes.storageClassName }}
  accessModes:                      
    - ReadWriteOnce                 
  resources:                        
    requests:                       
      storage: 1Gi                  
