apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-deployment"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ .Values.appName }}-deployment"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.appName }}-selector"
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: "{{ .Values.appName }}-selector"
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.ports.containerPort }}
          volumeMounts:
            - mountPath: {{ .Values.volumes.documents.pvc.mount }}
              name: {{ .Values.volumes.documents.name }}
            - mountPath: {{ .Values.volumes.db.pvc.mount }}
              name: {{ .Values.volumes.db.name }}
      volumes:
        - name: {{ .Values.volumes.documents.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.documents.pvc.claimName }}
        - name: {{ .Values.volumes.db.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.db.pvc.claimName }}
