version: '3'

networks:
  default:
    name: nginx-services

volumes:
  moodledb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local

services:
  moodle:
    image: docker.io/bitnami/moodle:4.2
    container_name: moodle
    ports:
      - '8080:8080'
    environment:
      - MOODLE_DATABASE_TYPE=pgsql
      - MOODLE_DATABASE_HOST=moodle_db
      - MOODLE_DATABASE_PORT_NUMBER=5432
      - MOODLE_DATABASE_NAME=${MOODLE_DB_NAME}
      - MOODLE_DATABASE_USER=${MOODLE_DB_USER}
      - MOODLE_DATABASE_PASSWORD=${MOODLE_DB_PASS}
      - MOODLE_USERNAME=${MOODLE_USER}
      - MOODLE_PASSWORD=${MOODLE_PASS}
      - PHP_UPLOAD_MAX_FILESIZE=8192M
      - PHP_POST_MAX_SIZE=8192M
      - PHP_ENABLE_OPCACHE=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - moodle_db
  moodle_db:
    image: postgres:14
    container_name: moodle_db
    restart: always
    volumes:
      - moodledb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${MOODLE_DB_NAME}
      - POSTGRES_USER=${MOODLE_DB_USER}
      - POSTGRES_PASSWORD=${MOODLE_DB_PASS}
