apiVersion: v1
kind: Service
metadata:
  name: "calorie-tracker-service"
  namespace: default
spec:
  selector:
    app: "calorie-tracker-selector"
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000
