{{- range $cronjob := $.Values.notificationJobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $cronjob.name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ $cronjob.name }}
    app.kubernetes.io/component: cronjob
    app.kubernetes.io/instance: api
spec:
  schedule: "{{ $cronjob.schedule }}"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ $cronjob.name }}
            image: mireknguyen/rss-notification
            imagePullPolicy: IfNotPresent
            args:
              - "-t"
              - "{{ $cronjob.title }}"
              - "-l"
              - "{{ $cronjob.link }}"
              - "-o"
              - "/out/{{ $cronjob.output }}"
            volumeMounts:
            - name: rss-volume
              mountPath: /out
          restartPolicy: OnFailure
          volumes:
          - name: rss-volume
            persistentVolumeClaim:
              claimName: rss-pvc
{{- end }}
