{{- range .Values.notificationJobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: notification-rss-cronjob
  namespace: {{ $.Values.namespace }}
spec:
  schedule: {{ .schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .name }}
            image: mireknguyen/rss-notification
            args:
              - "-t"
              - "{{ .title }}"
              - "-l"
              - "{{ .link }}"
              - "-o"
              - "/out/{{ .output }}"
            volumeMounts:
            - name: rss-volume
              mountPath: /out
          restartPolicy: OnFailure
          volumes:
          - name: rss-volume
            persistentVolumeClaim:
              claimName: rss-pvc
{{- end }}
