apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: youtube-api-key-external
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: youtube-api-key
  data:
    - secretKey: YOUTUBE_DATA_API_KEY
      remoteRef:
        key: "YOUTUBE_DATA_API_KEY"
