apiVersion: batch/v1
kind: CronJob
metadata:
  name: youtube-rss-cronjob
  namespace: {{ .Values.namespace }}
spec:
  schedule: "0 */3 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          {{- range .Values.jobs }}
          - name: {{ .name }}
            image: registry.hub.docker.com/mireknguyen/youtube-search
            args:
              - "--channel"
              - "{{ .channel }}"
              - "--playlist"
              - "{{ .playlist }}"
              - "-t"
              - "{{ .timezone }}"
              - "-r"
              - "{{ .rate }}"
              - "-o"
              - "/out/{{ .output }}"
            env:
            - name: YOUTUBE_DATA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: youtube-api-key
                  key: YOUTUBE_DATA_API_KEY
            volumeMounts:
            - name: rss-volume
              mountPath: /out
          {{- end }}
          restartPolicy: OnFailure
          volumes:
          - name: rss-volume
            persistentVolumeClaim:
              claimName: rss-pvc
