apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-deployment"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ .Values.appName }}-deployment"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.appName }}-selector"
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: "{{ .Values.appName }}-selector"
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.ports.containerPort }}
          volumeMounts:
            - name: nginx-proxy-config
              mountPath: /etc/nginx
      volumes:
        - name: nginx-proxy-config
          configMap:
            name: nginx-proxy-config
