apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.appName }}-ingress"
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.sslSecretName }}
  rules:
  {{- range .Values.ingress.hostPrefixes }}
  - host: "{{ .hostPrefix }}.{{ $.Values.ingress.host }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ $.Values.appName }}-service"
            port:
              number: {{ $.Values.ports.servicePort }}
  {{- end }}

