apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rss-pvc
  namespace: rss
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
