apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-deployment"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ .Values.appName }}-deployment"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.appName }}-selector"
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: "{{ .Values.appName }}-selector"
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 9091
            - containerPort: 51413
          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentials.secretName }}
                  key: USER
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentials.secretName }}
                  key: PASS
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - mountPath: {{ .Values.volumes.media.pvc.mount }}
              name: {{ .Values.volumes.media.name }}
      volumes:
        - name: {{ .Values.volumes.media.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.media.pvc.claimName }}
