replicas: 1
namespace: default
appName: flood

image:
  repository: jesec/flood
  tag: latest

ports:
  containerPort: 3000
  servicePort: 3000

volumes:
  config:
    name: config-data
    pvc:
      mount: /data
      claimName: flood-config-pvc
