apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MirekNguyen/self-hosted
    targetRevision: kubernetes
    path: services/radarr
    helm:
      valuesObject:
        replicas: 1
        namespace: default
        appName: radarr

        image:
          repository: linuxserver/radarr
          tag: latest

        ports:
          containerPort: 7878
          servicePort: 7878

        ingress:
          host: mirekng.com
          hostPrefix: radarr
          sslSecretName: ssl-certificate

        volumes:
          config:
            name: config-data
            pvc:
              mount: /config
              claimName: radarr-config-pvc
          media:
            name: media-data
            pvc:
              mount: /downloads
              claimName: media-pvc
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

