apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rss-proxy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MirekNguyen/self-hosted
    targetRevision: kubernetes
    path: services/rss-proxy
    helm:
      valuesObject:
        replicas: 1
        namespace: default
        appName: rss-proxy

        image:
          repository: nginx
          tag: stable

        ports:
          containerPort: 80
          servicePort: 80

        ingress:
          host: mirekng.com
          sslSecretName: ssl-certificate

        volumes:
          config:
            name: config-data
            pvc:
              mount: /etc/nginx
              claimName: nginx-config-pvc
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

