apiVersion: v1
kind: Service
metadata:
  name: transmission-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: transmission-selector
  ports:
    - protocol: TCP
      targetPort: 9091
      port: 9091
