apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-service"
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: "{{ .Values.appName }}-selector"
  ports:
    - protocol: TCP
      name: web-interface
      targetPort: 9091
      port: 9091
    - protocol: TCP
      name: torrent-tcp
      targetPort: 51413
      port: 51413
    - protocol: UDP
      name: torrent-udp
      targetPort: 51413
      port: 51413
