apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MirekNguyen/self-hosted
    targetRevision: kubernetes
    path: charts/argocd
    helm:
      valuesObject:
        namespace: argocd
        appName: argocd

        ingress:
          host: mirekng.com
          hostPrefix: argocd
          sslSecretName: ssl-certificate
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

