apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2024.10.4
    helm:
      values: |
        authentik:
          secret_key: "PleaseGenerateASecureKey"
          error_reporting:
            enabled: true
          postgresql:
            password: "ThisIsNotASecurePassword"
        server:
          ingress:
            ingressClassName: nginx
            enabled: false
            hosts:
              - authentik.mirekng.com
        postgresql:
          enabled: true
          auth:
            password: "ThisIsNotASecurePassword"
        redis:
          enabled: true
          image: 
            tag: 7.2.4-debian-12-r12
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


