apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bazarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MirekNguyen/self-hosted
    targetRevision: kubernetes
    path: charts/bazarr
    helm:
      valuesObject:
        replicas: 1
        namespace: default
        appName: bazarr

        image:
          repository: linuxserver/bazarr
          tag: latest

        ports:
          containerPort: 6767
          servicePort: 6767

        ingress:
          host: mirekng.com
          hostPrefix: bazarr
          sslSecretName: ssl-certificate

        volumes:
          config:
            name: config-data
            pvc:
              mount: /config
              claimName: bazarr-config-pvc
          media:
            name: media-data
            pvc:
              mount: /downloads
              claimName: media-pvc
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
