apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flood
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MirekNguyen/self-hosted
    targetRevision: kubernetes
    path: charts/flood
    helm:
      valuesObject:
        replicas: 0
        namespace: default
        appName: flood

        image:
          repository: jesec/flood
          tag: latest

        ports:
          containerPort: 3000
          servicePort: 3000

        ingress:
          host: mirekng.com
          hostPrefix: flood
          sslSecretName: ssl-certificate

        volumes:
          config:
            name: config-data
            pvc:
              mount: /data
              claimName: flood-config-pvc
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
