apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: freshrss
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MirekNguyen/self-hosted
    targetRevision: kubernetes
    path: charts/freshrss
    helm:
      valuesObject:
        replicas: 1
        namespace: default
        appName: freshrss

        image:
          repository: lscr.io/linuxserver/freshrss
          tag: latest

        ports:
          containerPort: 80
          servicePort: 80

        ingress:
          host: mirekng.com
          hostPrefix: rss
          sslSecretName: ssl-certificate

        volumes:
          config:
            name: config-data
            pvc:
              mount: /config
              claimName: freshrss-config-pvc
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

