apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://immich-app.github.io/immich-charts
    chart: immich
    targetRevision: 0.8.4
    helm:
      valuesObject:
        immich:
          persistence:
            library:
              existingClaim: photos-pvc
        # server:
        #   ingress:
        #     main:
        #       enabled: true
        #       hosts:
        #         - host: photos.mirekng.com
        #       tls:
        #         - hosts:
        #           - mirekng.com
        #           secretName: ssl-certificate
        #           paths:
        #             - path: "/"
        postgresql:
          enabled: true
          primary:
            resourcePreset: large
        redis:
          enabled: true
        machine-learning:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
