apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/immich-app/immich-charts
    targetRevision: 0.13.1
    chart: immich
    helm:
      valuesObject:
        controllers:
          main:
            containers:
              main:
                image:
                  tag: v3.0.1
                env:
                  DB_HOSTNAME: immich-postgres-service
                  DB_PORT: "5432"
                  DB_DATABASE_NAME: immich
                  DB_USERNAME: immich
                  DB_PASSWORD: immich
                  REDIS_HOSTNAME: immich-valkey

        immich:
          persistence:
            library:
              existingClaim: photos-pvc

        valkey:
          enabled: true

        server:
          enabled: true
          ingress:
            main:
              enabled: true
              annotations:
                nginx.ingress.kubernetes.io/proxy-body-size: "0"
              hosts:
                - host: photos.mirekng.com
                  paths:
                    - path: "/"
                      service:
                        identifier: main
              tls:
                - secretName: ssl-certificate
                  hosts:
                    - photos.mirekng.com

        machine-learning:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
