apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyseerr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MirekNguyen/self-hosted
    targetRevision: kubernetes
    path: charts/jellyseerr
    helm:
      valuesObject:
        replicas: 1
        namespace: default
        appName: jellyseerr

        image:
          repository: ghcr.io/seerr-team/seerr
          tag: v3.0.1

        ports:
          containerPort: 5055
          servicePort: 5055

        ingress:
          host: mirekng.com
          hostPrefix: jellyseerr
          sslSecretName: ssl-certificate

        podSecurityContext:
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch

        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
          seccompProfile:
            type: RuntimeDefault

        initContainers:
          - name: fix-permissions
            image: alpine:latest
            command: ["sh", "-c", "chown -R 1000:1000 /app/config"]
            volumeMounts:
              - mountPath: /app/config
                name: jellyseerr-config

        volumes:
          config:
            name: jellyseerr-config
            pvc:
              mount: /app/config
              claimName: jellyseerr-config-pvc
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

