apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: librechat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bat-bs/helm-charts.git
    targetRevision: main
    path: charts/librechat
    helm:
      valuesObject:
        librechat:
          configEnv:
            ALLOW_REGISTRATION: "false"
            ALLOW_SOCIAL_LOGIN: "false"
            ALLOW_SOCIAL_REGISTRATION: "false"
            ENDPOINTS: "openAI,assistants,azureOpenAI,bingAI,google,gptPlugins,anthropic"
            ANTHROPIC_MODELS: "claude-3-5-sonnet-20240620,claude-3-opus-20240229,claude-3-sonnet-20240229,claude-3-haiku-20240307,claude-2.1,claude-2,claude-1.2,claude-1,claude-1-100k,claude-instant-1,claude-instant-1-100k"
            GOOGLE_MODELS: "gemini-1.5-flash-latest,gemini-1.0-pro,gemini-1.0-pro-001,gemini-1.0-pro-latest,gemini-1.0-pro-vision-latest,gemini-1.5-pro-latest,gemini-pro,gemini-pro-vision"
            OPENAI_MODELS: "gpt-4o,chatgpt-4o-latest,gpt-4o-mini,gpt-3.5-turbo-0125,gpt-3.5-turbo-0301,gpt-3.5-turbo,gpt-4,gpt-4-0613,gpt-4-vision-preview,gpt-3.5-turbo-0613,gpt-3.5-turbo-16k-0613,gpt-4-0125-preview,gpt-4-turbo-preview,gpt-4-1106-preview,gpt-3.5-turbo-1106,gpt-3.5-turbo-instruct,gpt-3.5-turbo-instruct-0914,gpt-3.5-turbo-16k"
            DEBUG_OPENAI: "false"
            OPENAI_TITLE_MODEL: "gpt-3.5-turbo"
            OPENAI_SUMMARIZE: "true"
            OPENAI_SUMMARY_MODEL: "gpt-3.5-turbo"
            ASSISTANTS_API_KEY: "user_provided"
            ASSISTANTS_MODELS: "o1-preview,o1-preview-2024-09-12,o1-mini,o1-mini-2024-09-12,gpt-4o,gpt-4o-mini,gpt-3.5-turbo-0125,gpt-3.5-turbo-16k-0613,gpt-3.5-turbo-16k,gpt-3.5-turbo,gpt-4,gpt-4-0314,gpt-4-32k-0314,gpt-4-0613,gpt-3.5-turbo-0613,gpt-3.5-turbo-1106,gpt-4-0125-preview,gpt-4-turbo-preview,gpt-4-1106-preview"
            PLUGIN_MODELS: "gpt-4o,gpt-4o-mini,gpt-4,gpt-4-turbo-preview,gpt-4-0125-preview,gpt-4-1106-preview,gpt-4-0613,gpt-3.5-turbo,gpt-3.5-turbo-0125,gpt-3.5-turbo-1106,gpt-3.5-turbo-0613"
            DEBUG_PLUGINS: "true"
            SEARCH: "true"
            MEILI_NO_ANALYTICS: "true"
            OPENAI_MODERATION: "false"
            BAN_VIOLATIONS: "true"
            BAN_DURATION: "1000 * 60 * 60 * 2"
            BAN_INTERVAL: "20"
            LOGIN_VIOLATION_SCORE: "1"
            REGISTRATION_VIOLATION_SCORE: "1"
            CONCURRENT_VIOLATION_SCORE: "1"
            MESSAGE_VIOLATION_SCORE: "1"
            NON_BROWSER_VIOLATION_SCORE: "20"
            LOGIN_MAX: "7"
            LOGIN_WINDOW: "5"
            REGISTER_MAX: "5"
            REGISTER_WINDOW: "60"
            LIMIT_CONCURRENT_MESSAGES: "true"
            CONCURRENT_MESSAGE_MAX: "2"
            LIMIT_MESSAGE_IP: "true"
            MESSAGE_IP_MAX: "40"
            MESSAGE_IP_WINDOW: "1"
            LIMIT_MESSAGE_USER: "false"
            MESSAGE_USER_MAX: "40"
            MESSAGE_USER_WINDOW: "1"
            ILLEGAL_MODEL_REQ_SCORE: "5"
            CHECK_BALANCE: "false"
            ALLOW_EMAIL_LOGIN: "true"
            ALLOW_PASSWORD_RESET: "false"
            ALLOW_UNVERIFIED_EMAIL_LOGIN: "true"
            SESSION_EXPIRY: "1000 * 60 * 15"
            REFRESH_TOKEN_EXPIRY: "(1000 * 60 * 60 * 24) * 7"
            ALLOW_SHARED_LINKS: "true"
            ALLOW_SHARED_LINKS_PUBLIC: "true"
            APP_TITLE: "LibreChat"
            HELP_AND_FAQ_URL: "https://librechat.ai"
        ingress:
          enabled: true
          hosts:
            - host: librechat.mirekng.com
              paths:
                - path: "/"
                  pathType: ImplementationSpecific
          tls:
            - hosts:
              - mirekng.com
              secretName: ssl-certificate
        mongodb:
          image:
            registry: ghcr.io
            repository: xavidop/mongodb
            tag: '7.0'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
