apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: librechat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bat-bs/helm-charts.git
    targetRevision: main
    path: charts/librechat
    helm:
      valuesObject:
        librechat:
          configEnv:
            ALLOW_REGISTRATION: "true"
            ALLOW_SOCIAL_LOGIN: "true"
            ALLOW_SOCIAL_REGISTRATION: "true"
            ENDPOINTS: "openAI,assistants,azureOpenAI,bingAI,google,gptPlugins,anthropic"
        ingress:
          enabled: true
          hosts:
            - host: librechat.mirekng.com
              paths:
                - path: "/"
                  pathType: ImplementationSpecific
          tls:
            - hosts:
              - mirekng.com
              secretName: ssl-certificate
        mongodb:
          image:
            registry: ghcr.io
            repository: xavidop/mongodb
            tag: '7.0'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
