apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mirekng
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MirekNguyen/self-hosted
    targetRevision: kubernetes
    path: charts/mirekng
    helm:
      valuesObject:
        replicas: 2
        namespace: default
        appName: mirekng

        image:
          repository: mireknguyen/mirekng-homepage 
          tag: latest

        ports:
          containerPort: 3000
          servicePort: 3000

        ingress:
          host: mirekng.com
          sslSecretName: ssl-certificate

        env:
          mailer:
            name: NEXT_PUBLIC_MAILER_API
            value: ''
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
