apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-proxy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MirekNguyen/self-hosted
    targetRevision: kubernetes
    path: charts/nginx-proxy
    helm:
      valuesObject:
        replicas: 1
        namespace: default
        appName: nginx-proxy

        image:
          repository: nginx
          tag: stable

        ports:
          containerPort: 80
          servicePort: 80

        ingress:
          host: mirekng.com
          hostPrefixes:
            - hostPrefix: crm
            - hostPrefix: notes
          sslSecretName: ssl-certificate
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

