apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MirekNguyen/self-hosted
    targetRevision: kubernetes
    path: charts/prowlarr
    helm:
      valuesObject:
        replicas: 1
        namespace: default
        appName: prowlarr

        image:
          repository: linuxserver/prowlarr
          tag: latest

        ports:
          containerPort: 9696
          servicePort: 9696

        ingress:
          host: mirekng.com
          hostPrefix: prowlarr
          sslSecretName: ssl-certificate

        volumes:
          config:
            name: config-data
            pvc:
              mount: /config
              claimName: prowlarr-config-pvc
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

