apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MirekNguyen/self-hosted
    targetRevision: kubernetes
    path: charts/qbittorrent
    helm:
      valuesObject:
        replicas: 1
        namespace: default
        appName: qbittorrent

        image:
          repository: linuxserver/qbittorrent
          tag: latest

        ingress:
          host: mirekng.com
          hostPrefix: qbittorrent
          sslSecretName: ssl-certificate

        volumes:
          media:
            name: media-data
            pvc:
              mount: /downloads
              claimName: media-pvc
          config:
            name: config
            pvc:
              mount: /config
              claimName: qbittorrent-config-pvc
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

