apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-cluster
  namespace: argocd
spec:
  project: default
  sources:
    - chart: rook-ceph-cluster
      repoURL: https://charts.rook.io/release
      targetRevision: 1.16.2
      helm:
        values: |
          operatorNamespace: rook-ceph
          cephClusterSpec:
            mon:
              allowMultiplePerNode: true
              count: 1
            mgr:
              allowMultiplePerNode: true
              count: 1
            dashboard:
              ingressClassName: traefik
              tls:
              - hosts:
                - rook.mirekng.com
                secretName: ssl-certificate
          cephFileSystems:
            - name: ceph-filesystem
              spec:
                metadataPool:
                  replicated:
                    size: 1
                dataPools:
                  - failureDomain: host
                    replicated:
                      size: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
