apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rss-generator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MirekNguyen/self-hosted
    targetRevision: kubernetes
    path: charts/rss-generator
    helm:
      valuesObject:
        replicas: 1
        namespace: rss
        appName: rss-generator

        image:
          repository: nginx
          tag: latest

        ports:
          containerPort: 80
          servicePort: 80

        ingress:
          host: mirekng.com
          hostPrefix: feed
          sslSecretName: ssl-certificate

        volumes:
          rss:
            name: rss-volume
            pvc:
              mount: /usr/share/nginx/html
              claimName: rss-pvc
        jobs:
          - name: herdyn-youtube-rss
            channel: UCBJY0_6cB6q1THgfokwpQxA
            playlist: UUBJY0_6cB6q1THgfokwpQxA
            timezone: Europe/Prague
            rate: "20"
            output: herdyn.xml

          - name: ludwig-youtube-rss
            channel: UCrPseYLGpNygVi34QpGNqpA
            playlist: UUrPseYLGpNygVi34QpGNqpA
            timezone: Europe/Prague
            rate: "20"
            output: ludwig.xml

          - name: ludwin-youtube-rss
            channel: UCrPseYLGpNygVi34QpGNqpA
            playlist: UUrPseYLGpNygVi34QpGNqpA
            timezone: Europe/Prague
            rate: "20"
            output: ludwig.xml
        notificationJobs:
          - name: neovim-rss
            schedule: 0 0 * * 2
            title: Neovim
            link: https://www.reddit.com/r/neovim/top/?t=month
            output: neovim.xml

          - name: work-news-rss
            schedule: 0 0 * * 2
            title: Work news
            link: https://rss.mirekng.com/
            output: work-news.xml

          - name: genshin-leaks-rss
            schedule: 0 0 * * 2
            title: Genshin leaks
            link: https://www.reddit.com/r/Genshin_Impact_Leaks/new/
            output: genshin-leaks.xml
  destination:
    server: https://kubernetes.default.svc
    namespace: rss
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
