apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-certificate
  namespace: default
spec:
  secretName: ssl-certificate
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - 'mirekng.com'
    - '*.mirekng.com'
